### ISSUE TITLE
Can This Be Used To Converted A Local Hosts File To An LSRuleset?

### ISSUE THREAD

**Issue by SainteCelery** [tastapod/snitcher#2]
Hi. How might I adapt this to replace SB's list URL with that of one of my local hosts files?

**Comment by tastapod** [comment]
You can run the `snitcher.sh` script against any URL, including a local `file://` URL. The only criteria is that any blacklisted host names should have the IP address `0.0.0.0` in the hosts file.

So you can clone the repository and then run something like this:

    URL='file:///path/to/my/hosts' NAME='My hosts file' ./snitcher.sh > my_hosts.lsrules

Note: this is similar to [this line in update.sh](https://github.com/tastapod/snitcher/blob/58e00053a06f998a1e8d6a07fc936f27c68d0289/update.sh#L19).
