### ISSUE TITLE
Certificate error on rules.snitcher.dannorth.net

### ISSUE THREAD

**Issue by oscar-c** [tastapod/snitcher#3]
When Little Snitch tries to download the rule at https://rules.snitcher.dannorth.net/unified.lsrules , it reports there's an SSL error.
It looks like that server at rules.snitcher.dannorth.net is using a certificate for jbehave.org.

**Comment by tastapod** [comment]
Thanks, good catch! Rebuilt the config with `certbot` so it should be working now. Can you check please, and then I can close the issue?

**Comment by oscar-c** [comment]
It's working now. Thanks!
